name: Build STM32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ARM Toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make

      - name: Build firmware
        run: make