name: Build STM32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ARM Toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make

      - name: Build firmware
        run: make

      - name: Generate .bin from .elf
        run: arm-none-eabi-objcopy -O binary firmware.elf firmware.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
        name: firmware
        path: |
        firmware.elf
        firmware.bin